# An example of configuration for the calculator
---
# The location of home folder
home: '/home/<USER_NAME>/'  # <-- Change this accordingly!
# Input file names (CSV)
signals:
  - 'io.calc/in/example-1-input.csv'
  - 'io.calc/in/example-2-input.csv'
  - 'io.calc/in/example-3-input.csv'
  - 'io.calc/in/example-4-input.csv'
# Indicate if the first row of the CSV input files contains column titles (yes / no).
headers: yes
# Output file names (CSV)
results:
  - 'io.calc/out/example-1-fifo.csv'
  - 'io.calc/out/example-2-fifo.csv'
  - 'io.calc/out/example-3-fifo.csv'
  - 'io.calc/out/example-4-fifo.csv'
###### PARAMETERS #############################################################
# Note: same parameters for all inputs.
# Starting assets, cash initially allocated for trading
cash: 100000000
# Limit of exposure per position
# limit: 100000000  # <-- No multiple positions simultaneously open
limit: 50000000  # 1/2 cash allocated for trading <-- Max 2 positions simultaneously open
# limit: 20000000  # 1/5 cash allocated for trading <-- Max 5 positions simultaneously open
# Broker's commission
commission: 0.007  # 0.007 = 0.002 + 0.01 / 2
# commission: 0
...
